services:
  - type: web
    name: web-alert
    env: docker
    dockerCommand: node backend/server.js
    buildCommand: npm install
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: dpg-culanb8gph6c73d9jl50-a
      - key: DB_USER
        value: sail1
      - key: DB_PASSWORD
        value: 5p2GYOeXinvhRvhfOjkK30zItFISFcxs
      - key: DB_NAME
        value: sail_exks
      - key: DB_PORT
        value: "5432"
      - key: PORT
        value: "3000"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome"
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 